language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install .
script:
  - python setup.py test
deploy:
  provider: pypi
  user: glorpen
  password:
    secure: "JOE42a8vA60PDzqkVKgxNHOuPJ97saKsrxRt/YTU4tbMRQl86W5U0Ce5Kq5R2vM5jhAmat4naPFszyT5A8yGZ/1BZ3GeSzCh9EFAfgtp64AtAolc8m9bw2Q7bdSaNO93MGd7p6M3TJY/UcOywAdSDF4DR7dPwxAa4Sdjkx2R3eIiJm1gfc40tQDRx8L7GYJFOR2wg/BdXmDFT1LDtl6siGMbn1joE1mW/bmDPsCwfflrco3de/rjaZiBqP7F0MCCk8t2O91n+0yHFAr9Mw5t+WZzdSVJEsQZP877A37eIPdcR55/0k0YLoFf62Z2fjSp1JMHnCLSWgfGHRhMr8weoDK3JuRtFQKPrVWwtR218iS19UG/eN3WakgW6Ebkxofyd3FT9qSg79FoYBsRMc6ieFY0IpkiWox+tr621BGkdSroYz6a7afFW/dLRlKUU2FCqNmFhmaZXOLWpoYK3XA5Oz+tiOhySWixrzGuv+hvt2GOfyC7WzTqyb+OCGWK3z3Ftrv++8G3qtHzZmyrBbT6ElLfcuKzJuPuTlMtLuSqKSuGOqKEZAowAbw49JudDvVL1zSAB8tq59ee79acnGfaoqCjrT0+cuXZd/JsDTOD2KNZaVHrMdtvuWsM4JlIqtXYx3qangUeV2WPkjW68kaebCeZH/ULtzTK7ebXQAahwT8="
  on:
    tags: true
    branch: master
    python: '3.6'
    condition: "$TRAVIS_TAG =~ ^v[0-9.]+$"
  distributions: "sdist bdist_wheel"
